### ISSUE TITLE
오탈자 문의드립니다.

### ISSUE THREAD

**Issue by bactoria** [cheese10yun/springboot-oauth2#1]
안녕하세요.

![image](https://user-images.githubusercontent.com/25674959/48422224-8c09bf00-e7a1-11e8-8dc9-79d01aa50db2.png)

Spring Boot 2.1 에 시큐리티 5.1이 들어오지 않았나요?

(앞에 암호화방식이 바뀐것도 5.1 부터인지는 잘 모르겠네요)

&nbsp;

Spring Boot 2.1의 dependencies 에 `spring-boot-starter-oauth2-client` 이 들어왔던데

혹시 사용해 보셨는지요 ?

전 Spring Boot 2.1에서 소셜 인증이 계속 실패해서  2.0 으로 공부하고 있습니다ㅋㅋ

&nbsp;

요즘 oauth2 공부하는데 도움 많이 받았습니다. 감사합니다

**Comment by cheese10yun** [comment]
@bactoria 
감사합니다. Spring Security 5.1이 주입되는 게 맞습니다. 
5.0부터 암호화 관련된 것들이 변경돼서 5.0으로 표시했었네요
잘못된 정보는 수정 완료했습니다. 진심으로 감사드립니다.
